#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raaj2045/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raaj2045/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-777663183022"
  bucket_path: "docker-react"
  on:
    branch: master
